defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.finetune.train_ppo_gaussian_agent.TrainPPOGaussianAgent

name: ${env_name}_ft_gaussian_mlp_ta${horizon_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/furniture-finetune/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: ${oc.env:DPPO_LOG_DIR}/furniture-pretrain/round_table/round_table_med_dim_pre_gaussian_mlp_ta8/2024-06-28_16-26-38/checkpoint/state_3000.pt
normalization_path: ${oc.env:DPPO_DATA_DIR}/furniture/${env.specific.furniture}_${env.specific.randomness}/normalization.pth

seed: 42
device: cuda:0
env_name: ${env.specific.furniture}_${env.specific.randomness}_dim
obs_dim: 44
action_dim: 10
cond_steps: 1
horizon_steps: 8
act_steps: 8

env:
  n_envs: 1000
  name: ${env_name}
  env_type: furniture
  max_episode_steps: 1000
  best_reward_threshold_for_success: 2
  specific:
    headless: true
    furniture: round_table
    randomness: med
    normalization_path: ${normalization_path}
    obs_steps: ${cond_steps}
    act_steps: ${act_steps}
    sparse_reward: True

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: furniture-${env.specific.furniture}-${env.specific.randomness}-finetune
  run: ${now:%H-%M-%S}_${name}

train:
  n_train_itr: 1000
  n_critic_warmup_itr: 1
  n_steps: ${eval:'round(${env.max_episode_steps} / ${act_steps})'}
  gamma: 0.999
  actor_lr: 1e-5
  actor_weight_decay: 0
  actor_lr_scheduler:
    first_cycle_steps: 10000
    warmup_steps: 10
    min_lr: 1e-6
  critic_lr: 1e-3
  critic_weight_decay: 0
  critic_lr_scheduler:
    first_cycle_steps: 10000
    warmup_steps: 10
    min_lr: 1e-3
  save_model_freq: 50
  val_freq: 10
  render:
    freq: 1
    num: 0
  # PPO specific
  reward_scale_running: True
  reward_scale_const: 1.0
  gae_lambda: 0.95
  batch_size: 8800
  update_epochs: 5
  vf_coef: 0.5
  target_kl: 1

model:
  _target_: model.rl.gaussian_ppo.PPO_Gaussian
  clip_ploss_coef: 0.01
  randn_clip_value: 3
  network_path: ${base_policy_path}
  actor:
    _target_: model.common.mlp_gaussian.Gaussian_MLP
    mlp_dims:
    - 1024
    - 1024
    - 1024
    - 1024
    - 1024
    - 1024
    - 1024
    - 1024
    - 1024
    - 1024
    - 1024
    activation_type: ReLU
    residual_style: True
    fixed_std: 0.04
    learn_fixed_std: True
    std_min: 0.01
    std_max: 0.2
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
  critic:
    _target_: model.common.critic.CriticObs
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    mlp_dims: [512, 512, 512]
    activation_type: Mish
    residual_style: True
  horizon_steps: ${horizon_steps}
  device: ${device}